/* eslint-disable @typescript-eslint/no-explicit-any */
export const productResponse: any = {
  id: "12345",
  query: "I'm looking for books about WWII intelligence operations",
  messages: [
    {
      type: "User",
      id: "ea76b6e1-2649-4fb5-86f2-704ab4079c7c",
      query_id: "40607ece-baf3-42e4-b397-da5bdc00b229",
      conversation_id: "60552f05-f4ac-4bce-9065-3c61f03da3e8",
      user_id: "c5163446-4eff-5c3f-b362-33932ca630d4",
      payload: {
        type: "text",
        metadata: {},
        code: {
          language: "",
          title: "",
          text: "",
        },
        objects: ["I'm looking for books about WWII intelligence operations"],
      },
    },
    {
      type: "text",
      id: "tex-5f7ad2fe-fc16-4337-9b71-1ddfb9a5b04b",
      user_id: "c5163446-4eff-5c3f-b362-33932ca630d4",
      conversation_id: "60552f05-f4ac-4bce-9065-3c61f03da3e8",
      query_id: "40607ece-baf3-42e4-b397-da5bdc00b229",
      payload: {
        type: "response",
        metadata: {},
        objects: [
          {
            text: "I will now search the Library collection for intelligence history books.",
          },
        ],
      },
    },
    {
      type: "text",
      id: "tex-0b1ee47f-698c-4859-9a4b-1fb52d572a8c",
      user_id: "c5163446-4eff-5c3f-b362-33932ca630d4",
      conversation_id: "60552f05-f4ac-4bce-9065-3c61f03da3e8",
      query_id: "40607ece-baf3-42e4-b397-da5bdc00b229",
      payload: {
        type: "response",
        metadata: {},
        objects: [
          {
            text: 'I\'m performing a hybrid search on the `Library` collection for "WWII intelligence operations" within the description field.',
          },
        ],
      },
    },
    {
      type: "result",
      user_id: "c5163446-4eff-5c3f-b362-33932ca630d4",
      conversation_id: "60552f05-f4ac-4bce-9065-3c61f03da3e8",
      query_id: "40607ece-baf3-42e4-b397-da5bdc00b229",
      id: "res-e48c1c51-3231-4ab0-8d48-002b7279a8cf",
      payload: {
        type: "ecommerce",
        objects: [
          // Sorted by rating (highest first), books without rating at the end
          {
            id: "americas-secret-army",
            name: "America's Secret Army: The Untold Story of the Counterintelligence Corps",
            description:
              "By the authors of 'Nazi Gold,' this book describes the exploits of the secret American Counter Intelligence Corps, both during and after World War II. It recounts their work against enemy espionage, their role in hunting down Nazi war criminals, and their spy network behind the Iron Curtain.",
            author: "Douglas Botting, Ian Sayer",
            brand: "Douglas Botting",
            publisher: "CreateSpace Independent Publishing Platform",
            year: 1990,
            pages: 430,
            isbn_10: "1984349848",
            isbn_13: "978-1984349842",
            rating: 5.0,
            language: "English",
            image: "/assets/books/america-s-secret-army.jpg",
            buy_link:
              "https://www.amazon.com/Americas-Secret-Army-Untold-Counterintelligence/dp/1984349848",
            category: "History & Intelligence",
            collection: "American Intelligence",
            tags: ["WWII", "Cold War", "Intelligence History", "OSINT Research"],
            uuid: "8f5ebb68-5c74-55c9-8ede-9e6eb59ed05e",
          },
          {
            id: "oesterreich-zwischen-den-maechten",
            name: "Österreich zwischen den Mächten: Schweizer Berichte aus Wien 1938–1955",
            description:
              "Die politische Berichterstattung der schweizerischen Vertretung in Wien während des Anschlusses, des Zweiten Weltkriegs und der alliierten Besatzung.",
            author: "Bernd Haunfelder",
            brand: "Bernd Haunfelder",
            publisher: "DDS",
            pages: 652,
            isbn_10: "3906051161",
            isbn_13: "978-3906051161",
            rating: 5.0,
            language: "German",
            image: "/assets/books/oesterreich-zwischen-den-maechten.jpg",
            buy_link: "https://www.amazon.de/dp/3906051161",
            category: "History & Intelligence",
            collection: "Diplomatic Reports",
            tags: ["WWII", "Cold War", "Intelligence History", "OSINT Research"],
            uuid: "eb619644-1bae-56fc-9fd2-7d8957b363ca",
          },
          {
            id: "the-ratline-love-lies-and-justice-on-the-trail-of-a-nazi-fugitive",
            name: "The Ratline: Love, Lies and Justice on the Trail of a Nazi Fugitive",
            description:
              "A gripping investigation into the life and death of Otto von Wächter, a Nazi war criminal who escaped justice through the Vatican ratlines.",
            author: "Philippe Sands",
            brand: "Philippe Sands",
            publisher: "Orion Publishing Group",
            year: 2020,
            pages: 432,
            isbn_10: "1474608124",
            isbn_13: "978-1474608121",
            rating: 4.5,
            language: "English",
            image: "/assets/books/the-ratline.jpg",
            buy_link: "https://www.amazon.com/dp/1474608124",
            category: "History & Intelligence",
            collection: "WWII & Cold War",
            tags: ["WWII", "Cold War", "Intelligence History", "OSINT Research"],
            uuid: "9a66d0eb-8fa0-5179-83f6-85c8ffb5d3f0",
          },
          {
            id: "smersh-stalins-secret-weapon",
            name: "SMERSH: Stalin's Secret Weapon",
            description:
              "A gripping history of Stalin's military intelligence service filled with new details on previously unknown operations and the brutal characters of the Soviet secret world.",
            author: "Vadim J. Birstein",
            brand: "Vadim J. Birstein",
            publisher: "Biteback Publishing",
            year: 2013,
            pages: 528,
            isbn_10: "1849545677",
            isbn_13: "978-1849545679",
            rating: 4.3,
            language: "English",
            image: "/assets/books/smersh-stalin-s-secret-weapon.jpg",
            buy_link:
              "https://www.amazon.com/SMERSH-Stalins-Secret-Military-Counterintelligence/dp/1849545677",
            category: "History & Intelligence",
            collection: "Soviet Intelligence",
            tags: ["WWII", "Cold War", "Intelligence History", "OSINT Research"],
            uuid: "e839a80b-ed33-5fb0-9541-0e94911fb55f",
          },
          {
            id: "the-red-army-in-austria",
            name: "The Red Army in Austria: The Soviet Occupation, 1945–1955",
            description:
              "Based on a broad array of sources from Russian and Austrian archives, this collection provides a comprehensive analysis of the Soviet occupation of Austria from 1945 to 1955. The contributors cover a wide range of topics, including the Soviet Secret Services, the military kommandaturas, Soviet occupation policies, the withdrawal of troops in 1955, everyday life, the image of 'the Russians,' violence against women, arrests, deportations, Soviet aid provisions, as well as children of occupation.",
            author: "Stefan Karner, Barbara Stelzl-Marx (Editors)",
            brand: "Stefan Karner",
            publisher: "Lexington Books",
            year: 2020,
            pages: 286,
            isbn_10: "1793626588",
            isbn_13: "978-1793626585",
            rating: 4.0,
            language: "English",
            series: "Harvard Cold War Studies",
            image: "/assets/books/the-red-army-in-austria.jpg",
            buy_link:
              "https://www.amazon.it/Red-Army-Austria-Occupation-1945-1955/dp/1793626588",
            category: "History & Intelligence",
            collection: "Soviet Occupation",
            tags: ["WWII", "Cold War", "Intelligence History", "OSINT Research"],
            uuid: "cc5ac477-a2a8-54cb-8992-4ba3293b40ee",
          },
          {
            id: "rattenlinien-german-edition",
            name: "Rattenlinien (German Edition)",
            description:
              "Ein packender Kriminalroman über die Fluchtrouten der Nazis nach dem Zweiten Weltkrieg - die sogenannten Rattenlinien.",
            author: "Martin von Arndt",
            brand: "Martin von Arndt",
            publisher: "Ars Vivendi",
            pages: 304,
            isbn_10: "386913724X",
            isbn_13: "978-3548289676",
            rating: 4.0,
            language: "German",
            image: "/assets/books/rattenlinien-german-edition.jpg",
            buy_link: "https://www.amazon.de/dp/386913724X",
            category: "History & Intelligence",
            collection: "Nazi Escape Routes",
            tags: ["WWII", "Cold War", "Intelligence History", "OSINT Research"],
            uuid: "1e1649c9-fa2f-5183-9100-138939e88833",
          },
          {
            id: "dark-mysteries-of-the-vatican",
            name: "Dark Mysteries of the Vatican",
            description:
              "A riveting investigation into the controversial secrets and scandals hidden within Vatican walls, from Nazi gold to modern-day intrigue.",
            author: "H. Paul Jeffers",
            brand: "H. Paul Jeffers",
            publisher: "Kensington",
            year: 2010,
            pages: 210,
            isbn_10: "0806531320",
            isbn_13: "978-0806531328",
            rating: 3.8,
            language: "English",
            image: "/assets/books/dark-mysteries-of-the-vatican.jpg",
            buy_link: "https://www.amazon.com/dp/0806531320",
            category: "History & Intelligence",
            collection: "Vatican & Ratlines",
            tags: ["WWII", "Cold War", "Intelligence History", "OSINT Research"],
            uuid: "c3d496b4-2477-5f5f-854d-c1bf466a9512",
          },
          {
            id: "stalins-letzte-opfer",
            name: "Stalins letzte Opfer: Verschleppte und erschossene Österreicher in Moskau 1950–1953",
            description:
              "Stalins letzte Opfer dokumentiert das Schicksal österreichischer Zivilisten, die in der Nachkriegszeit von sowjetischen Behörden verschleppt und in Moskau hingerichtet wurden.",
            author: "Stefan Karner, Barbara Stelzl-Marx",
            brand: "Stefan Karner",
            publisher: "Oldenbourg Böhlau",
            year: 2009,
            pages: 676,
            isbn_10: "320578281X",
            isbn_13: "978-3205782810",
            language: "German",
            image: "/assets/books/stalins-letzte-opfer.jpg",
            buy_link:
              "https://www.abebooks.com/servlet/BookDetailsPL?bi=31763489925",
            category: "History & Intelligence",
            collection: "Soviet Occupation",
            tags: ["WWII", "Cold War", "Intelligence History", "OSINT Research"],
            uuid: "c7c13f12-4182-5592-bac7-5e8e681fb4cc",
          },
          {
            id: "nkvd-kgb-activities",
            name: "NKVD/KGB Activities and Their Cooperation with Other Secret Services in Central and Eastern Europe 1945–1989",
            description:
              "Academic study of NKVD/KGB operations and cooperation with secret services across Central and Eastern Europe during the Cold War period.",
            author: "Alexandra Grúňová (Editor)",
            brand: "Alexandra Grúňová",
            publisher: "Nation's Memory Institute",
            isbn_10: "8089335055",
            isbn_13: "978-8089335053",
            language: "English",
            image: "/assets/books/nkvd-kgb-activities.jpg",
            buy_link: "https://books.google.it/books?id=G9qCjwEACAAJ",
            category: "History & Intelligence",
            collection: "Soviet Intelligence",
            tags: ["WWII", "Cold War", "Intelligence History", "OSINT Research"],
            uuid: "85919daf-ef82-58bb-ac5d-e3e1cf36ed02",
          },
        ],
        metadata: {
          collection_name: "Library",
          display_type: "ecommerce",
          needs_summarising: false,
          query_text: "WWII intelligence operations",
          query_type: "hybrid",
          chunked: false,
          query_output: {
            target_collections: ["Library"],
            search_type: "hybrid",
            search_query: "WWII intelligence operations",
            sort_by: null,
            filter_buckets: null,
            limit: 10,
          },
          code: {
            language: "python",
            title: "Query",
            text: "collection.query.hybrid(\n    query='WWII intelligence operations',\n    limit=10\n)",
          },
        },
        code: {
          language: "python",
          title: "Query",
          text: "collection.query.hybrid(\n    query='WWII intelligence operations',\n    limit=10\n)",
        },
      },
    },
    {
      type: "text",
      id: "tex-d6a796e7-66be-4bb1-ab76-de01f9e884f0",
      user_id: "c5163446-4eff-5c3f-b362-33932ca630d4",
      conversation_id: "60552f05-f4ac-4bce-9065-3c61f03da3e8",
      query_id: "40607ece-baf3-42e4-b397-da5bdc00b229",
      payload: {
        type: "response",
        metadata: {},
        objects: [
          {
            text: "I will now summarize the search results for WWII intelligence books from the Library collection.",
          },
        ],
      },
    },
    {
      type: "text",
      id: "tex-c6b3d2e1-433b-4a89-b012-d8a468ca4973",
      user_id: "c5163446-4eff-5c3f-b362-33932ca630d4",
      conversation_id: "60552f05-f4ac-4bce-9065-3c61f03da3e8",
      query_id: "40607ece-baf3-42e4-b397-da5bdc00b229",
      payload: {
        type: "text_with_citations",
        metadata: {
          title: "Intelligence History Books Available",
        },
        objects: [
          {
            text: "Several excellent books on WWII and Cold War intelligence operations are available in the Library collection, covering topics from Nazi escape routes to Soviet counterintelligence.\n",
            ref_ids: [],
          },
          {
            text: 'For Nazi ratlines and escape routes, consider "The Ratline" by Philippe Sands, a gripping investigation into Otto von Wächter\'s escape through Vatican networks. "Dark Mysteries of the Vatican" by H. Paul Jeffers explores similar Vatican-related secrets and scandals.\n',
            ref_ids: ["query_Library_0_0", "query_Library_0_5"],
          },
          {
            text: 'For Soviet intelligence history, "SMERSH: Stalin\'s Secret Weapon" by Vadim J. Birstein provides new details on previously unknown operations. "The Red Army in Austria" covers the Soviet occupation from 1945 to 1955 with contributions from both Russian and Austrian archives.\n',
            ref_ids: ["query_Library_0_1", "query_Library_0_3"],
          },
          {
            text: '"America\'s Secret Army" by Douglas Botting and Ian Sayer describes the exploits of the American Counter Intelligence Corps, their work against enemy espionage, and their role in hunting down Nazi war criminals.\n',
            ref_ids: ["query_Library_0_2"],
          },
        ],
      },
    },
    {
      type: "suggestion",
      id: "7288e77e-ada2-4f1a-8c45-66125cf338e4",
      conversation_id: "60552f05-f4ac-4bce-9065-3c61f03da3e8",
      query_id: "40607ece-baf3-42e4-b397-da5bdc00b229",
      user_id: "com-f058bc92-fb59-4180-bafd-e013897ba2f7",
      payload: {
        error: "",
        suggestions: [],
      },
    },
  ],
  finished: true,
  query_start: new Date(),
  query_end: new Date(Date.now() + 1000),
  NER: {
    text: "I'm looking for books about WWII intelligence operations",
    noun_spans: [],
    entity_spans: [],
  },
  feedback: 1,
  index: 0,
};
