/* eslint-disable @typescript-eslint/no-explicit-any */
export const tableResponse: any = {
  id: "tbl-ratlines-fugitives-001",
  query: "What are the documented roles and attributed deaths for Nazi fugitives who escaped via rat lines?",
  messages: [
    {
      type: "User",
      id: "80411939-2ea8-4178-bd22-2a6f834556e7",
      query_id: "2663dacf-4c10-4351-b753-8cf78c8b16a6",
      conversation_id: "30fb6699-81de-42b1-a190-f74f5dd351f7",
      user_id: "c5163446-4eff-5c3f-b362-33932ca630d4",
      payload: {
        type: "text",
        metadata: {},
        code: {
          language: "",
          title: "",
          text: "",
        },
        objects: [
          "What are the documented roles and attributed deaths for Nazi fugitives who escaped via rat lines?",
        ],
      },
    },
    {
      type: "text",
      id: "tex-87a426aa-b1f3-40a3-8bdd-91a843c06f9b",
      user_id: "c5163446-4eff-5c3f-b362-33932ca630d4",
      conversation_id: "30fb6699-81de-42b1-a190-f74f5dd351f7",
      query_id: "2663dacf-4c10-4351-b753-8cf78c8b16a6",
      payload: {
        type: "response",
        metadata: {},
        objects: [
          {
            text: "I will query the ELYSIA_ENTITIES collection for Nazi fugitives with their roles and academically documented attribution data from the Rat Lines corpus.",
          },
        ],
      },
    },
    {
      type: "text",
      id: "tex-abb234dd-eafb-4bab-bf07-610bddb2ba5f",
      user_id: "c5163446-4eff-5c3f-b362-33932ca630d4",
      conversation_id: "30fb6699-81de-42b1-a190-f74f5dd351f7",
      query_id: "2663dacf-4c10-4351-b753-8cf78c8b16a6",
      payload: {
        type: "response",
        metadata: {},
        objects: [
          {
            text: "I will filter for persons with perpetrator roles and include their responsibility type (direct, command, or logistical) per scholarly consensus.",
          },
        ],
      },
    },
    {
      type: "result",
      user_id: "c5163446-4eff-5c3f-b362-33932ca630d4",
      conversation_id: "30fb6699-81de-42b1-a190-f74f5dd351f7",
      query_id: "2663dacf-4c10-4351-b753-8cf78c8b16a6",
      id: "res-c7373331-c3d8-44fc-a81c-dd4ed6dce383",
      payload: {
        type: "table",
        objects: [
          {
            name: "Ante Pavelić",
            role: "Head of State",
            rank: "Poglavnik (NDH)",
            responsibility_type: "Command",
            regime_deaths_low: 300000,
            regime_deaths_high: 500000,
            scholarly_note: "Ustasha regime total; Jasenovac camp primary site",
            escape_year: 1945,
            escape_route: "Austria → Rome → Buenos Aires",
            destination: "Argentina → Spain",
            fate: "Died 1959 in Madrid from assassination wounds",
            source: "USHMM; Naimark (2001)",
            confidence_score: 0.9,
            uuid: "166d5332-18e5-56a1-bd67-2b2fd7544b1c",
            _REF_ID: "query_ELYSIA_ENTITIES_0_0",
          },
          {
            name: "Walter Rauff",
            role: "Gas Van Developer",
            rank: "SS-Standartenführer",
            responsibility_type: "Technical/Command",
            regime_deaths_low: 50000,
            regime_deaths_high: 100000,
            scholarly_note: "Gas van program; estimates vary due to incomplete records",
            escape_year: 1949,
            escape_route: "Vatican ratline → Syria → Ecuador → Chile",
            destination: "Chile",
            fate: "Died 1984, never extradited despite requests",
            source: "Browning (2004); Angrick (2018)",
            confidence_score: 0.85,
            uuid: "d43287ae-4d09-55f9-ad1b-a93b1ead616c",
            _REF_ID: "query_ELYSIA_ENTITIES_0_1",
          },
          {
            name: "Josef Mengele",
            role: "Camp Physician",
            rank: "SS-Hauptsturmführer",
            responsibility_type: "Direct",
            regime_deaths_low: 700,
            regime_deaths_high: 3000,
            scholarly_note: "618 documented twin victims; 63 noma victims; selection role unclear",
            escape_year: 1949,
            escape_route: "South Tyrol → Genoa → Buenos Aires",
            destination: "Argentina → Paraguay → Brazil",
            fate: "Died 1979, drowned in Brazil",
            source: "Weindling (2016); HGS (2023)",
            confidence_score: 0.9,
            uuid: "2db012e2-b6d6-5714-bf3d-47b31a5eb8ee",
            _REF_ID: "query_ELYSIA_ENTITIES_0_2",
          },
          {
            name: "Klaus Barbie",
            role: "Gestapo Chief, Lyon",
            rank: "SS-Hauptsturmführer",
            responsibility_type: "Direct/Command",
            regime_deaths_low: 300,
            regime_deaths_high: 1000,
            scholarly_note: "44 Izieu children documented; hundreds tortured; 1987 trial evidence",
            escape_year: 1951,
            escape_route: "CIC ratline → Genoa → Buenos Aires → La Paz",
            destination: "Bolivia",
            fate: "Extradited to France 1983, convicted 1987",
            source: "Bower (1984); 1987 Lyon Trial",
            confidence_score: 0.95,
            uuid: "3b539abf-5da2-5e24-b533-d721f09d9526",
            _REF_ID: "query_ELYSIA_ENTITIES_0_3",
          },
        ],
        metadata: {
          collection_name: "ELYSIA_ENTITIES",
          display_type: "table",
          needs_summarising: false,
          query_text: null,
          query_type: "filter_only",
          chunked: false,
          query_output: {
            target_collections: ["ELYSIA_ENTITIES"],
            search_type: "filter_only",
            search_query: null,
            sort_by: {
              property_name: "regime_deaths_high",
              direction: "descending",
            },
            filter_buckets: {
              responsibility_type: ["Direct", "Command", "Technical/Command", "Direct/Command"],
            },
            limit: 4,
          },
          code: {
            language: "python",
            title: "Query",
            text: "collection.query.fetch_objects(\n    filters=Filter.by_property('responsibility_type').contains_any(\n        ['Direct', 'Command', 'Technical/Command', 'Direct/Command']\n    ),\n    limit=4,\n    sort=Sort.by_property(\n        'regime_deaths_high',\n        ascending=False\n    )\n)",
          },
        },
        code: {
          language: "python",
          title: "Query",
          text: "collection.query.fetch_objects(\n    filters=Filter.by_property('responsibility_type').contains_any(\n        ['Direct', 'Command', 'Logistical', 'Technical/Command']\n    ),\n    limit=5,\n    sort=Sort.by_property(\n        'regime_deaths_high',\n        ascending=False\n    )\n)",
        },
      },
    },
    {
      type: "text",
      id: "tex-4fb0f6b1-188f-41b0-9623-5ba2c84d0c16",
      user_id: "c5163446-4eff-5c3f-b362-33932ca630d4",
      conversation_id: "30fb6699-81de-42b1-a190-f74f5dd351f7",
      query_id: "2663dacf-4c10-4351-b753-8cf78c8b16a6",
      payload: {
        type: "response",
        metadata: {},
        objects: [
          {
            text: "I am creating a summary based on scholarly consensus, noting that historians provide ranges rather than precise counts due to incomplete documentation.",
          },
        ],
      },
    },
    {
      type: "text",
      id: "tex-8ff90132-8223-4373-aeef-283fa64a085b",
      user_id: "c5163446-4eff-5c3f-b362-33932ca630d4",
      conversation_id: "30fb6699-81de-42b1-a190-f74f5dd351f7",
      query_id: "2663dacf-4c10-4351-b753-8cf78c8b16a6",
      payload: {
        type: "text_with_citations",
        metadata: {
          title: "Nazi Fugitives: Roles and Attributed Deaths (Scholarly Consensus)",
        },
        objects: [
          {
            text: "**Ante Pavelić** as Poglavnik of the Independent State of Croatia (NDH) bears command responsibility for the Ustasha genocide. Scholarly estimates attribute **300,000–500,000 deaths** to the regime, primarily at Jasenovac concentration camp, targeting Serbs, Jews, and Roma.\n\n",
            ref_ids: ["query_ELYSIA_ENTITIES_0_0"],
          },
          {
            text: "**Walter Rauff** developed and deployed mobile gas vans used primarily by Einsatzgruppen. Scholarly estimates attribute **50,000–100,000 deaths** to the gas van program, though documentation is fragmentary.\n\n",
            ref_ids: ["query_ELYSIA_ENTITIES_0_1"],
          },
          {
            text: "**Josef Mengele** conducted human experiments at Auschwitz. Research has documented **618 twin victims** and **63 noma experiment victims** by name. His role in camp selections remains under-documented; total direct victims are estimated in the **hundreds to low thousands**.\n\n",
            ref_ids: ["query_ELYSIA_ENTITIES_0_2"],
          },
          {
            text: "**Klaus Barbie** commanded Gestapo operations in Lyon. His 1987 trial documented responsibility for the **44 Izieu children** deported to Auschwitz, plus **hundreds tortured** and killed. Total documented victims number **300–1,000**.\n\n",
            ref_ids: ["query_ELYSIA_ENTITIES_0_3"],
          },
          {
            text: "All four fugitives escaped via Vatican-facilitated rat lines between 1945–1951. Only Barbie faced trial; the others died in exile. Victim counts reflect scholarly ranges based on available documentation—precise totals remain unavailable for most perpetrators.",
            ref_ids: [],
          },
        ],
      },
    },
    {
      type: "suggestion",
      id: "dfcfff0e-1c11-44a7-b005-688480e2eff0",
      conversation_id: "30fb6699-81de-42b1-a190-f74f5dd351f7",
      query_id: "2663dacf-4c10-4351-b753-8cf78c8b16a6",
      user_id: "c5163446-4eff-5c3f-b362-33932ca630d4",
      payload: {
        error: "",
        suggestions: [
          "What sources document the Jasenovac death toll?",
          "How did Eichmann's trial establish his organizational role?",
          "Which archives contain gas van deployment records?",
        ],
      },
    },
  ],
  finished: true,
  query_start: new Date(),
  query_end: new Date(Date.now() + 1000),
  NER: {
    text: "What are the documented roles and attributed deaths for Nazi fugitives who escaped via rat lines?",
    noun_spans: [
      [18, 23],
      [28, 45],
      [50, 64],
    ],
    entity_spans: [[50, 54]],
  },
  feedback: 2,
  index: 0,
};
